travis:
  secure:
    BINSTAR_TOKEN: QfFFepcnQZOrZLeZhoZg9Uj8vePlTG7cXMMsdH24KVV9PnDp7ZyUlQ4wgh7aUd9/d2X4B99S9RhimpxnunGpNRrmJ0Q7vvG0pIRefrmfWTZlnfNQEGzqRg90McQdHnj1cQmmoiqp+qh90ZyzOpYA2yZ0cu919lFPcH50pfHNJfRJ/EnbHlraIrTAuo5S+rH9VuZHtnsgSeeMzePXEgYTEGZ39lGlU6iyHiMMYnuKokNCj/4pCM3ovWkEnCJ12WWCXLBjQeOlwlwXS18vlZxVETU4c5yA3PfIr60I0zbVMsQXNds/bnKceDdWCUYNWAzr+P6n2/YZb3X/Gfgs/Tq0GWwIIGMs9Z5GqIhNofniL4BB4OdXdGuBBHifYYdsTv3twSmgFsnxa03eCUIEebmHNy11hR1oloF+23qjDi9SJKMAi1kodMhgOsQsYZWQIuF7C+LGYPQD4zUoAxfMplvk3C2E/3tU5TI8KOf6Ff+QTnEpV7i/90vM0JsEMRfDS3Ux33Ps1r9PG59D5/6153jAMF3441dNkOiTeY6pigsEg98V2k+WR2d5gmy/OE7lW8k1VQ3p7948tLpzQ6T1KYqkXj4WIsAuZnoUjhR+ewor9S2NrqOK7ASFlNPcRfIytPzb8jif2gYqKt4DfMZFTmLPqXRob6anTKvN5YfBcDx7bNg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
